from __future__ import annotations

from typing import Dict, Iterable, Set

TABLE_FILES: Dict[str, str] = {
    "trades": "trades.csv",
    "positions": "positions.csv",
    "equity_books_daily": "equity_books_daily.csv",
    "book_daily_attribution": "book_daily_attribution.csv",
    "allocator_rejections_daily": "allocator_rejections_daily.csv",
    "allocator_state_changes": "allocator_state_changes.csv",
    "book_metrics": "book_metrics.csv",
    "strategy_metrics_by_book": "strategy_metrics_by_book.csv",
    "exit_reason_attribution": "exit_reason_attribution.csv",
}

MIN_REQUIRED_FILES = {
    TABLE_FILES["trades"],
}

REQUIRED_COLUMNS: Dict[str, Set[str]] = {
    "trades": {
        "date",
        "symbol",
        "strategy",
        "book",
        "allocator_state",
        "exit_r",
        "peak_r",
        "giveback_r",
        "reason",
        "position_id",
        "entry_id",
    },
    "positions": {
        "position_id",
        "entry_id",
        "book",
        "strategy",
        "symbol",
        "entry_date",
        "exit_date",
        "entry_price",
        "exit_price",
        "holding_days",
        "initial_risk",
        "adds_taken",
        "mfe_r",
        "mae_r",
        "peak_r",
        "exit_r",
        "giveback_r",
        "exit_reason",
        "realized_pnl",
        "return_pct",
        "costs_commission",
        "costs_slippage",
        "allocator_state_at_entry",
        "allocator_state_at_exit",
        "risk_budget_pct_at_entry",
        "risk_budget_dollars_at_entry",
    },
    "equity_books_daily": {
        "date",
        "equity_total",
        "equity_dollars_core",
        "equity_dollars_convex",
        "allocator_state_core",
        "allocator_state_convex",
        "open_risk_dollars_core",
        "open_risk_dollars_convex",
        "gross_exposure_core",
        "gross_exposure_convex",
        "risk_budget_reference_core",
        "risk_budget_reference_convex",
    },
    "book_daily_attribution": {
        "date",
        "book",
        "daily_pnl",
        "pnl_total",
        "book_index",
        "open_risk_dollars",
        "gross_exposure",
        "allocator_state",
        "risk_budget_reference",
    },
    "allocator_rejections_daily": {
        "date",
        "book",
        "signals_seen",
        "accepted",
    },
    "allocator_state_changes": {
        "date",
        "book",
        "prev_state",
        "new_state",
        "trigger",
        "book_drawdown_pct",
        "portfolio_drawdown_pct",
        "risk_budget_before",
        "risk_budget_after",
    },
    "book_metrics": {
        "book",
        "initial_equity",
        "final_equity",
        "total_return_pct",
        "annualized_return_pct",
        "annualized_volatility_pct",
        "sharpe_ratio",
        "sortino_ratio",
        "calmar_ratio",
        "max_drawdown_pct",
        "time_in_market_pct",
        "turnover_pct",
        "total_trades",
        "win_rate_pct",
        "avg_win",
        "avg_loss",
        "profit_factor",
        "avg_holding_days",
        "avg_trade_return_pct",
        "payoff_ratio",
        "expectancy",
        "total_pnl",
        "total_commission",
        "total_slippage_cost",
    },
    "strategy_metrics_by_book": {
        "book",
        "strategy",
        "trades",
        "win_rate_pct",
        "total_pnl",
        "avg_pnl",
        "avg_win",
        "avg_loss",
        "profit_factor",
        "avg_holding_days",
        "avg_trade_return_pct",
        "total_return_pct",
        "annualized_return_pct",
        "payoff_ratio",
        "expectancy",
        "max_consecutive_losses",
        "pct_peak_r_ge_1",
        "pct_exit_ge_0_5r_given_peak_1",
    },
    "exit_reason_attribution": {
        "book",
        "reason",
        "count",
        "win_rate_pct",
        "total_pnl",
        "avg_exit_r",
        "avg_peak_r",
        "avg_giveback_r",
    },
}

DATE_COLUMNS: Dict[str, Iterable[str]] = {
    "trades": ["date", "entry_date"],
    "positions": ["entry_date", "exit_date"],
    "equity_books_daily": ["date"],
    "book_daily_attribution": ["date"],
    "allocator_rejections_daily": ["date"],
    "allocator_state_changes": ["date"],
}
