import numpy as np
import pandas as pd

from stock_screener.core.strategy import BaseStrategy
from strategy_backtester.core.engine import BacktestEngine


def _trend_df(rows: int = 120, start_price: float = 100.0) -> pd.DataFrame:
    idx = pd.date_range("2020-01-01", periods=rows, freq="D")
    close = pd.Series(np.linspace(start_price, start_price + 10, rows), index=idx)
    open_ = close.shift(1).fillna(close) * 0.999
    high = pd.concat([open_, close], axis=1).max(axis=1) + 0.25
    low = pd.concat([open_, close], axis=1).min(axis=1) - 0.25
    volume = pd.Series(1_000_000, index=idx, dtype="float")
    return pd.DataFrame({"Open": open_, "High": high, "Low": low, "Close": close, "Volume": volume})


class DummyTrendStrategy(BaseStrategy):
    """
    Simple always-on long strategy used to validate the vectorized backtest loop.
    """

    sentiment = "BULLISH"
    use_take_profit = False
    use_exit_signal = False
    use_time_stop = False
    use_regime_exit = False

    def check(self, df: pd.DataFrame):
        return bool(df["Close"].iloc[-1] > df["Open"].iloc[-1]), {}

    def signal(self, df: pd.DataFrame) -> pd.Series:
        return df["Close"] > df["Open"]

    def stop_loss_series(self, df: pd.DataFrame) -> pd.Series:
        return (df["Close"] * 0.98).round(2)

    def exit_signal(self, df: pd.DataFrame) -> pd.Series:
        return pd.Series(False, index=df.index)


class _FakeDataProvider:
    def __init__(self, data_map):
        self.data_map = data_map

    def fetch_batch_data(self, *_, **__):
        return self.data_map


def test_vectorized_backtest_runs_on_prefetched_data():
    price_df = _trend_df()
    data = {
        "AAA": price_df,
        "SPY": price_df,
        "MES=F": price_df,  # hedge symbol
    }
    strategy = DummyTrendStrategy()
    engine = BacktestEngine(
        start_date="2020-01-10",
        end_date="2020-02-20",
        universe=["AAA"],
        strategies=[strategy],
        use_vectorized=True,
        trade_size=10_000,
        risk_per_trade_pct=0.02,
        hedge_symbol="MES=F",
        regime_symbol="SPY",
        min_avg_dollar_vol=0.0,
        min_avg_volume_futures=0.0,
        allow_risk_off_entries=True,
        exit_on_risk_off=False,
    )
    engine.data_provider = _FakeDataProvider(data)
    engine.screener.data_provider = engine.data_provider

    engine.run()
    equity_df, trades_df, summary, by_strategy, by_ticker = engine.get_report()

    assert not equity_df.empty, "Equity curve should be recorded"
    assert not trades_df.empty, "Trades should be generated by vectorized loop"
    assert summary.get("total_return_pct") is not None
    assert "AAA" in set(by_ticker["symbol"])
    assert strategy.get_name() in set(by_strategy["strategy"])
